export const chatData = [
  {
    id: 1,
    name: "Nick Logan",
    info: "PHP,SQLite,Artisan CLI",
    post: "Outlines keep you honest. They stop you from indulging in poorly thought-out metaphor about driving and keep you focused on the overall structure of your post",
    img: "../../300-23.jpg",
    comment: 120,
    like: 15,
  },
  {
    id: 2,
    name: "Carles Nilson",
    info: "Yesterday at 5:06 PM",
    post: "Outlines keep you honest. They stop you from indulging in poorly thought-out metaphor about driving and keep you focused on the overall structure of your post",
    img: "../../300-21.jpg",
    comment: 12,
    like: 150,
  },
  {
    id: 3,
    name: "Carles Nilson",
    info: "Last week at 10:00 PM",
    post: "Outlines keep you honest. They stop you from indulging in poorly thought-out metaphor about driving and keep you focused on the overall structure of your post",
    img: "../../300-11.jpg",
    comment: 22,
    like: 59,
  },
  {
    id: 4,
    name: "Sam Logan",
    info: "Mango,Java,Python",
    post: "Outlines keep you honest. They stop you from indulging in poorly thought-out metaphor about driving and keep you focused on the overall structure of your post",
    img: "../../300-21.jpg",
    comment: 89,
    like: 29,
    postimg: "../../20.jpg",
  },
  {
    id: 5,
    name: "Mat Dillon",
    info: "Last Month",
    post: "Outlines keep you honest. They stop you from indulging in poorly thought-out metaphor",
    img: "../../300-14.jpg",
    comment: 189,
    like: 229,
  },
];
